backend/urls.py
from django.urls import path

from . import views

app_name = "backend"

urlpatterns = [
    path('', views.Register.as_view(), name="register"),
    path('accounts/logout', views.logout_view, name="logout"),
    path('accounts/login', views.login_view.as_view(), name="login"),
    path('accounts/register', views.Register.as_view(), name="register"),
    path('stocks/list', views.StockList.as_view(), name="StockList"),
    path('stocks/buy/<int:stock_id>', views.BuyStock.as_view(), name="buy"),
    path('stocks/sell/<int:stock_id>', views.SellStock.as_view(), name="sell"),
    path('leaderboard', views.LeaderBoard.as_view(), name="leaderboard"),
]

goldenhack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
]

backend/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    credits = models.IntegerField(default=10000)
    transactions = models.ManyToManyField('Transaction', related_name="stocks_bought_or_sold", blank=False)
    friends = models.ManyToManyField('User', blank=True)
    profit = models.IntegerField(default=0)

#To be extracted by the API

# API

class Stock(models.Model):
    name = models.CharField(max_length=100, default="stock", blank=False, null=False)
    description = models.CharField(max_length=200, default="stocks", blank=False, null=False)


DEFAULT_USER_ID = 1
class Transaction(models.Model):
    stock = models.ForeignKey(Stock, default=DEFAULT_USER_ID, null=False, blank=False, related_name="STOCK_ID", on_delete=models.CASCADE)
    user = models.ForeignKey(User, default=DEFAULT_USER_ID, null=False, blank=False, related_name="Operation_Performed_By", on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0, null=False, blank=False)
    #API
    totalExpenditure = models.IntegerField(default=0, blank=False, null=False)

class TransactionHistory(models.Model):
    user = models.OneToOneField(User, default=DEFAULT_USER_ID, primary_key=True, null=False, blank=False, related_name="Transaction_By", on_delete=models.CASCADE)
    intialQuantity = models.IntegerField(default=0, null=False, blank=False)
    finalQuantity = models.IntegerField(default=0, null=False, blank=False)
    stockQuote = models.CharField(max_length=100, default="stock", blank=False, null=False)
    priceAtWhichBought = models.IntegerField(default=0, null=False, blank=False)
    priceAtWhichSold = models.IntegerField(default=0, null=False, blank=False)
    intialCredits = models.IntegerField(default=0, null=False, blank=False)
    finalCredits = models.IntegerField(default=0, null=False, blank=False)

    class Meta:
        verbose_name_plural = "Transaction History"
        db_table = "Transaction_History"

backend/forms.py
from django import forms

from .models import User

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username']

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

backend/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from .models import Stock, Transaction, User, TransactionHistory
from .stockapi import intraday as intraday


from .forms import LoginForm, RegisterForm

# Create your views here.
def index(request):
    return HttpResponse("HELLO WORLD!!")

# display all stocks present in the database
class StockList(View, LoginRequiredMixin):
    template = "backend/stock_list.html"

    def get(self, request):
        stocks = Stock.objects.all()
        return render(request, self.template, {
            'stocks': stocks,
        })

class login_view(View):
    template = "backend/login.html"
    success_url = "backend:StockList"

    def get(self, request):
        form = LoginForm()
        return render(request, self.template, {
            'form': form,
            'message': "Welcome!!, Please login to get access to all features",
        })

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=uname, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse_lazy(self.success_url))
            else:
                return render(request, self.template, {
                    'form': LoginForm(),
                    'message': "Invalid username or password",
                })
        else:
            return render(request, self.template, {
                'form': LoginForm(),
                'message': "Please Enter all fields",
            })

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("backend:register"))

class Register(View):
    template = 'backend/register.html'

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template, {
            'form': form,
            'message': 'Please Enter Your UserName',
        })

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
            p1 = form.cleaned_data["password"]
            p2 = form.cleaned_data["confirm_password"]
            if not p1 == p2:
                return render(request, self.template, {
                    'form': RegisterForm(),
                    'message': "Passwords don't match",
                })
            try:
                user = User.objects.create_user(uname, first_name=first_name, last_name=last_name, email=email, password=p1)
                user.save()

            except IntegrityError:
                return render(request, self.template, {
                    'form': RegisterForm(),
                    'message': "An Account With This User Name Already Exists",
                })

            return HttpResponseRedirect(reverse("backend:StockList"))

# buy a particular stock and create a transaction
class BuyStock(View, LoginRequiredMixin):
    template = "backend/buy_stock.html"

    def get(self, request, stock_id):
        stock = Stock.objects.get(id=stock_id)
        # get stock price using stock.name and store in curr_price
        curr_price = curr_price = intraday(stock.name)
        return render(request, self.template, {
            'stock': stock,
            'price': curr_price,
        })

    # check if the stock id is present in user's transaction list
    def check_stock_id(self, request, stock_id):
        user = User.objects.get(username="test_account")
        transactions = user.transactions.all()
        for transaction in transactions:
            if transaction.stock.id == stock_id:
                return transaction
        return None

    def post(self, request, stock_id):
        stock = Stock.objects.get(id=stock_id)
        transaction = self.check_stock_id(request, stock_id)
        intialQuant = 0
        user = User.objects.get(username="test_account")

        if transaction is None:
            transaction = Transaction.objects.create(
                user=user,
                stock=stock,
                quantity=int(request.POST["shares"]),
                totalExpenditure=intraday(stock.name) * int(request.POST["shares"]),
            )
            intialQuant = 0
            transaction.save()
        else:
            intialQuant = transaction.quantity
            transaction.quantity += int(request.POST["shares"])
            transaction.totalExpenditure += intraday(stock.name)
            transaction.save()
            """
        transactionHistory = TransactionHistory.objects.create(
            user = user,
            intialQuantity = intialQuant,
            finalQuantity = intialQuant + int(request.POST["shares"]),
            stockQuote = stock.name,
            priceAtWhichBought = intraday(stock.name),
            intialCredits = user.credits,
            finalCredits = user.credits - intraday(stock.name),
        )
        transactionHistory.save()
        """
        user.credits -= intraday(stock.name)
        user.save()
        return HttpResponseRedirect(reverse("backend:StockList"))

# sell a particular stock and update that particular stock transaction and increase the user credits and user profit
class SellStock(View, LoginRequiredMixin):
    template = "backend/sell_stock.html"

    def get(self, request, stock_id):
        stock = Stock.objects.get(id=stock_id)
        # get stock price using stock.name and store in curr_price
        curr_price = intraday(stock.name)
        user = User.objects.get(username="test_account")
        try:
            transaction = Transaction.objects.get(user=user, stock=stock)
        except Transaction.DoesNotExist:
            return render(request, self.template, {
                'stocks': Stock.objects.all(),
                'message': "you don't own stocks of this company"
            })
        return render(request, self.template, {
                    'stock': stock,
                    'transaction': transaction,
                    'price': curr_price,
                })


    # check if the stock id is present in user's transaction list
    def check_stock_id(self, stock_id):
        user = User.objects.get(username="test_account")
        stock = Stock.objects.get(id=stock_id)
        transaction = Transaction.objects.get(user=user, stock=stock)
        return transaction


    def post(self, request, stock_id):
        stock = Stock.objects.get(id=stock_id)
        user = User.objects.get(username="test_account")
        transaction = self.check_stock_id(stock_id)
        if transaction is None:
            #show error that you don't have that stock
            return HttpResponseRedirect(reverse("backend:StockList"))
        else:
            intialQuant = transaction.quantity
            transaction.quantity -= int(request.POST["shares"])
            # update user credits and profit
            user.credits += intraday(stock.name)
            user.profit += intraday(stock.name)
            transaction.save()
            """
            transactionHistory = TransactionHistory.objects.create(
                user = user.id,
                intialQuantity = intialQuant,
                finalQuantity = intialQuant - request.quantity,
                stockQuote = stock.name,
                priceAtWhichSold = intraday(stock.name),
                intialCredits = user.credits,
                finalCredits = user.credits + intraday(stock.name)*request.quantity,
            )
            transactionHistory.save()
            """
            return HttpResponseRedirect(reverse("backend:StockList"))

# display all transactions and stocks owned by a user and (TODO) its transactions
class UserDashBoard(View, LoginRequiredMixin):
    template = "backend/user_dashboard.html"

    def get_transaction_history(self, request, userID):
        allTransactions = TransactionHistory.objects.raw(
            'SELECT * FROM Transaction_History WHERE user = %s', [userID]
        )

    def get(self, request):
        user = User.objects.get(username="test_account")
        transactions = user.transactions.all()
        # for each transaction, get the stock details and store them together
        stocksAndTransactionDetails = []
        for transaction in transactions:
            stock = Stock.objects.get(id=transaction.stock.id)
            # adding stock and transaction as one object in stocksAndTransactionDetails
            stocksAndTransactionDetails.append({
                'stock': stock,
                'transaction': transaction,
            })

        allTransactionDetials = get_transaction_history(self, request, user.id)


        return render(request, self.template, {
            'portfolioDetails': stocksAndTransactionDetails,
            'allTransactionDetials': allTransactionDetials,
        })

# user public profile in which we show the user's credits, profit and its total stocks owned
class UserProfile(View):
    template = "backend/user_profile.html"

    def user_Public_Profile(self, request, userID):
        user = User.objects.get(id=userID)
        transactions = user.transactions.all()
        totalExpenditure = 0
        stockDetails = []
        for transaction in transactions:
            totalExpenditure += transaction.totalExpenditure

backend/templates/backend/buy_stock.html
{% extends "backend/layout.html" %}

{% block title %}
    Quote
{% endblock %}

{% block main %}
    <form action="{% url 'backend:buy' stock.id %}" method="post">
      {% csrf_token %}
        <!-- TODO get stock symbol and value  -->
        <div class="form-group">
            <h1>{{ stock.name }}</h1>
            <p>{{ stock.description }}</p>
            <input autocomplete="off" autofocus class="form-control" name="shares" placeholder="Shares" type="number" min="1" required />
            <br>
            <input autofocus class="form-control" name="price" type="number" value="{{ price }}" readonly/>
        </div>
        <button class="btn btn-primary" type="submit">Buy</button>
    </form>
{% endblock %}

backend/templates/backend/layout.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- documentation at http://getbootstrap.com/docs/4.1/, alternative themes at https://bootswatch.com/ -->
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

        <!-- https://favicon.io/emoji-favicons/money-mouth-face/ -->
        <link href="/static/favicon.ico" rel="icon">

        <link href="{% static 'backend/styles.css' %}" rel="stylesheet">

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

        <title>Stocky {% block title %}{% endblock %}</title>

    </head>

    <body>

        <nav class="navbar navbar-expand-md navbar-light bg-light border">
            <a class="navbar-brand" href="{% url 'backend:StockList' %}"><span class="red">Stocky</span></a>
            <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbar" data-toggle="collapse" type="button">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav mr-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="#">History</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'backend:leaderboard' %}">LEADERBOARD</a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="/logout">Log Out</a></li>
                    </ul>
                {% else %}
                    <ul class="navbar-nav ml-auto mt-2">
                        <li class="nav-item"><a class="nav-link" href="/register">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="/login">Log In</a></li>
                    </ul>
                {% endif %}
            </div>
        </nav>

            <header>
                <div class="alert alert-primary border text-center" role="alert">
                      {{ message }}
                </div>
            </header>

        <main class="container p-5">
            {% block main %}{% endblock %}
        </main>

    </body>

</html>

backend/templates/backend/leaderboard.html
{% extends "backend/layout.html" %}

{% block title %}
    LEADERBOARD
{% endblock %}

{% block main %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Rank</th>
                <th>Username</th>
                <th>Credits</th>
                <th>Total Value Earned By Selling</th>
            </tr>
        </thead>
        <tbody>
            {% for details in usersAndProfit %}
                <tr>
                    <td>{{ details.rank }}</td>
                    <td>{{ details.name }}</td>
                    <td>{{ details.credits }}</td>
                    <td>{{ details.profit }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

backend/templates/backend/login.html
{% extends "backend/layout.html" %}

{% load crispy_forms_tags %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
    <form action="{% url 'backend:login' %}" method="post">
      {% csrf_token %}
        {{ form | crispy }}
        <br>
        <button class="btn btn-primary" type="submit">Log In</button>
    </form>
{% endblock %}

backend/templates/backend/register.html
{% extends "backend/layout.html" %}
{% load crispy_forms_tags %}

{% block title %}REGISTER{% endblock %}

{% block main %}
  <form action="{% url 'backend:register' %}" method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <br>
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
  <br>
  Already have an account? <a href="{% url 'backend:login' %}">Login Here</a>.
{% endblock %}

backend/templates/backend/sell_stock.html
{% extends "backend/layout.html" %}

{% block title %}
    Quote
{% endblock %}

{% block main %}
    <!-- display current quantity of stocks -->
    <h3>Current Stock Quantity: {{transaction.quantity}}</h3>
    <h3>Total Amount Bought of Stock: {{transaction.totalExpenditure}}</h3>
    <form action="{% url 'backend:sell' stock.id %}" method="post">
      {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" name="symbol"  value="{{ stock.name }}" readonly/>
        </div>
        <div class="form-group">
            <input autocomplete="off" autofocus class="form-control" name="shares" placeholder="Shares" type="number" min="1" required />
            <br>
            <input autocomplete="off" autofocus class="form-control" name="price" placeholder="price" min="1" value={{price}} />
        </div>
        <button class="btn btn-danger" type="submit">Sell</button>
    </form>
{% endblock %}

backend/templates/backend/stock_list.html
{% extends "backend/layout.html" %}

{% block title %}
    Stock Values
{% endblock %}

{% block main %}
  {% for stock in stocks %}
    <tr>
      <td><a href="{% url 'backend:buy' stock.id %}">{{ stock.name }}</a></td>
      <br>
      <td>{{ stock.description }}</td>
      <br>
      <a href="{% url 'backend:buy' stock.id %}">BUY</a> or <a href="{% url 'backend:sell' stock.id %}">SELL</a> if owned
      <br><br>
    </tr>
  {% endfor %}
{% endblock %}

backend/templates/backend/user_dashboard.html
{% extends "backend/layout.html" %}

{% block title %}
    Dashboard
{% endblock %}

{% block main %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Symbol</th>
                <th>Shares</th>
                <th>Price</th>
                <th>Transacted</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td>{{ transaction.symbol }}</td>
                    <td>{{ transaction.shares }}</td>
                    <td>{{ (transaction.shares * transaction.price_per_share) | abs | usd }}</td>
                    <td>{{ transaction.created_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}